### ISSUE TITLE
请问代码开源吗？准备采取什么协议发布？

### ISSUE THREAD

**Issue by Ji-Yuhang** [awehook/blink-mind-desktop#1]
我之前写了一点和 up 主功能差不多的。
https://github.com/Ji-Yuhang/workflowy
很期待能够参考下 up 主的代码

**Comment by awehook** [comment]
这个代码没有开源，因为这个代码在写的时候没有考虑到可扩展性。我开源了一个思维导图的库[blink-mind]( https://github.com/awehook/blink-mind), 这个库是支持插件的方式来进行扩展，只要写一个插件的话，思维导图也可以以大纲笔记的形式来展示，你可以参考一下这个库的代码，如果你感兴趣的话，可以去写一个插件来支持大纲笔记的展示形式。

**Comment by awehook** [comment]
源代码已经开源
