### ISSUE TITLE
我个人对这个项目很感兴趣，觉得很酷，想参与开发

### ISSUE THREAD

**Issue by myadmin** [awehook/blink-mind-desktop#10]
如题，请问能参与开发吗？

**Comment by myadmin** [comment]
@awehook

**Comment by awehook** [comment]
这个项目暂时没有文档，所以如果你能够愿意通过代码了解整体架构的话，也是可以的，你可以前期先看一下代码，然后有不懂的地方也可以讨论，你可以先通过邮件发送你的联系方式（微信）给我，然后我加你微信，建群讨论。

**Comment by awehook** [comment]
我的邮箱是awehook@163.com

**Comment by myadmin** [comment]
好的，已经给你发邮件了
