### ISSUE TITLE
Source not found

### ISSUE THREAD

**Issue by 1mm0rt41PC** [awehook/blink-mind-desktop#3]
Hello !

I can't find the source code, am I on the right repository?
is it possible to have the source code and instructions for build?
I'd like to add features: copy/paste image, copy/paste indented text to make nodes

Regards

**Comment by awehook** [comment]
The feature of copying and pasting pictures is now supported, but it needs to be added in the form of screenshots. The feature of selecting pictures from  file system and adding to topic  is planing to be implemented in a later version. Copy/paste indented text to make nodes is in progress and is expected to be released next week. The source code is not opened.

**Comment by 1mm0rt41PC** [comment]
Nice job !
Do you plan to release the source code ?
Which plugin did you use for the outliner and for the WYISWYG part ?

Best regards

**Comment by awehook** [comment]
There are no plans to release the source code.
The plugins of outliner and WYISWYG is not opend. 
WYISWYG now uses roosterjs (https://github.com/microsoft/roosterjs).

**Comment by awehook** [comment]
The source code is open now.
