### ISSUE TITLE
Use concurrently to avoid opening multiple terminals

### ISSUE THREAD

**Issue by Seanny123** [awehook/blink-mind-desktop#8]
Currently, to develop `blink-mind-desktop` three commands need to be run:
```bash
yarn dev:r
yarn dev:m
yarn start:m
```

Would you be interested in using [`concurrently`](https://github.com/kimmobrunfeldt/concurrently) to make it easier to run these three commands? I can make a PR if you find this solution acceptable.

**Comment by awehook** [comment]
The commands yarn dev:r and yarn dev:m can run concurrently, but the command yarn start:m need to wait for the previous two command to complete.
I opened the three terminals  so that the output of the three was not mixed, and the logs could be found more easily.
