### ISSUE TITLE
关于批量调整图片大小，焦点移动以及组织树状图

### ISSUE THREAD

**Issue by wxzdxds** [awehook/blink-mind-desktop#9]
我试了好多导图，这一款是我遇到的非常棒的导图了。
我在阅读小说时想要用思维导图理清里面的家谱以及家族地点势力图，但是
1. 家徽，即图片，非常的多，每次手动调节很麻烦，能不能加一个选中一张调好大小的图片后，将此图片的样式应用于所有图片的功能。
2. 按住ctrl可以上下键将焦点移到同级节点，那能不能移到父级节点或子节点呢。
3. 家谱图和组织结构图按我的思维直观来讲是向下生长的

我试过的好多思维导图软件，除了一些商业的外，只有这款最接近我的需求了，我觉得很棒

**Comment by awehook** [comment]
因为这个项目是我业余时间做的项目，由于个人开发进度无法满足很多人不同的需求，所以后面计划在整体架构上将项目做成可以加载插件的模式，这样的话，一些需求就可以通过开发插件来完成。

**Comment by wxzdxds** [comment]
嗯嗯，这样很好，我的想法也就是说说哈
